name: Set tag on a new version release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  set-tag-in-repo:
    if: github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: debug
        shell: bash
        run: |
          echo "Milestone: " ${{ github.event.pull_request.milestone.title }}

      - name: Set tag
        uses: actions/github-script@v5.1.0
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.pull_request.milestone.title }}',
              sha: context.sha
              })


# vi:et:sw=2
