name: Update TorrentMonitor version

on:
  schedule:
    - cron: 58 * * * *
  workflow_dispatch:

jobs:
  update_torrentmonitor:
    name: Update TorrentMonitor verions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Update torrentmonitor version
        id: downloadtorrentmonitor
        shell: bash
        run: |
          wget -q http://korphome.ru/torrent_monitor/tm-latest.zip -qO /tmp/tm-latest.zip
          unzip -q /tmp/tm-latest.zip -d /tmp/

          TM_VERSION=$(jq -r '.system' /tmp/TorrentMonitor-master/version.txt)
          echo "::set-output name=tm_version::${TM_VERSION}"

          DATE=$(head -n 1 /tmp/TorrentMonitor-master/changelog.txt | awk '{print $1;}')
          echo "::set-output name=date::${DATE}"

          sed "s/\(ENV VERSION=*\)[^ ]*/\1\"${TM_VERSION}\"/" < Dockerfile > /tmp/Dockerfile.tmp
          sed "s/\(    RELEASE_DATE=*\)[^ ]*/\1\"${DATE}\"/" < /tmp/Dockerfile.tmp > Dockerfile

          PR_BRANCH="tmupdatebot/torrentmonitorupdate-${TM_VERSION}"
          echo "::set-output name=pr_branch::${PR_BRANCH}"

          echo "Base pr_branch=${PR_BRANCH}, date=${DATE}, tm_version=${TM_VERSION}"

          TM_TAG='v${TM_VERSION}-1'
          echo "::set-output name=release_tag::${TM_TAG}"

      - name: Create Pull Request, Bump tm-latest.zip, torrentmonitor version ${{ steps.downloadtorrentmonitor.outputs.tm_version }}
        id: createpr
        uses: peter-evans/create-pull-request@v3.12.1
        with:
          branch: ${{ steps.downloadtorrentmonitor.outputs.pr_branch }}
          commit-message: TM -> ${{ steps.downloadtorrentmonitor.outputs.tm_version }}
          delete-branch: true
          title: Bump TM to version ${{ steps.downloadtorrentmonitor.outputs.tm_version }}
          body: |
            Bump tm-latest.zip, version ${{ steps.downloadtorrentmonitor.outputs.tm_version }}, date ${{ steps.downloadtorrentmonitor.outputs.date }}

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions
            release

      - name: Notify owner on Telegram
        if: ${{ steps.createpr.outputs.pull-request-number }}
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          message: |
            PR created for a new TM version ${{ steps.downloadtorrentmonitor.outputs.tm_version }}

            See details:
            ${{ steps.createpr.outputs.pull-request-url }}

      - name: Set tag ${{ steps.downloadtorrentmonitor.outputs.release_tag }}
        if: ${{ steps.createpr.outputs.pull-request-number }}
        uses: actions/github-script@v5.1.0
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.downloadtorrentmonitor.outputs.release_tag }}',
              sha: context.sha
              })

# vi:et:sw=2
